<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php
    echo $this->headTitle('Inditel ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false);
    echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
    echo $this->plugin('HeadLink');
    echo $this->plugin('HeadStyle');
    echo $this->plugin('HeadScript');
    ?>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand"
               href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Skeleton Application') ?></a>

            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li class="active"><a
                            href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <?php echo $this->content; ?>
    <hr>
    <footer>
        <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies
            Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
    </footer>
</div>
<?php echo $this->inlineScript() ?>
</body>
</html>
